"""history table

Revision ID: 2ae3bed30c3f
Revises: fe248d267f74
Create Date: 2023-03-04 18:13:26.753775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae3bed30c3f'
down_revision = 'fe248d267f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('bookmark', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_column('bookmark')
        batch_op.drop_column('title')
        batch_op.drop_column('url')

    # ### end Alembic commands ###
