"""questiontable

Revision ID: ef3f5900dd53
Revises: 2630ed85a52c
Create Date: 2023-03-12 19:50:32.197897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3f5900dd53'
down_revision = '2630ed85a52c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('own')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('own', sa.VARCHAR(length=1), nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
