"""history table

Revision ID: fe3c6d23d691
Revises: 2ae3bed30c3f
Create Date: 2023-03-09 18:50:11.433071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe3c6d23d691'
down_revision = '2ae3bed30c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.alter_column('bookmark',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.alter_column('bookmark',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)

    # ### end Alembic commands ###
